# ShortFactory Configuration

# Reddit API 설정
reddit:
  client_id: ${REDDIT_CLIENT_ID}
  client_secret: ${REDDIT_CLIENT_SECRET}
  user_agent: "ShortFactory/1.0.0"
  subreddits:
    - r/entitledparents
    - relationship_advice
  fetch_limit: 10
  fetch_interval: 3600  # 1시간 (초 단위)

# Google Sheets 설정
google_sheets:
  credentials_file: ${GOOGLE_SHEETS_CREDENTIALS_FILE}
  spreadsheet_id: ${SPREADSHEET_ID}
  worksheet_name: ${SHEET_NAME}
  max_rows: 1000

# LangChain 설정
langchain:
  model_name: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  templates_dir: "config/templates"

# 로깅 설정
logging:
  level: "INFO"  # 기본 로그 레벨
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file: "shortfactory.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  console_logging: true  # 콘솔 출력 활성화 여부
  file_logging: true    # 파일 출력 활성화 여부

# 상태 관리
status:
  states:
    - NEW
    - IN_PROGRESS
    - COMPLETE
    - ERROR
  history_enabled: true
  max_retries: 3

# 프로세스 설정
process:
  fetch:
    enabled: true
    concurrent_fetches: 1
  create:
    enabled: true
    concurrent_creates: 2
    batch_size: 5 