# Untold Backstory Creator Configuration
content_prompt: |
    Create a wild, visually magnetic, and hyper-engaging short video that uncovers the ridiculous, messed-up, or totally unexpected truth behind something everyone thinks they already understand — like a common object, brand, invention, daily habit, or internet trend.

    The video subject: {video_subject}
    
    Guidelines:
    - Final video must be 50–65 seconds (max)
    - Start with a scroll-stopping hook that feels like “Hold up… WHAT?!”
    - Tone: cheeky, punchy, fun, with just a pinch of sarcasm or chaos
    - Use cliffhangers, fast cuts, and unexpected phrasing to hold viewer attention
    - Every scene must push the viewer deeper into the “wait, seriously?” mindset
    - Humor should feel smart, relatable, and sometimes absurd — meme-worthy
    - Analogies, twists, pop culture callbacks = yes, yes, yes
    - Each script line should be short, snappy, and build curiosity or surprise
    - Use at least 9 beat-style scenes to keep it moving fast
    - End with a final twist or challenge that makes the viewer want to share it immediately

    Target Audience: Meme-fueled minds, fact addicts, YouTube/TikTok binge-watchers, people who say “I love weird history/science/facts”
    Core Principle: Flip the viewer’s understanding of something ordinary into “how did I not know this?!”
    Tone: Witty, fast-paced, wild-but-true, chaotic-but-clever
    Goal: Make the viewer shout “THERE’S NO WAY” then immediately hit replay or tag someone
    Structure: 
        1. 🔥 Hook — what you thought it was
        2. 🤨 But here’s what’s actually going on…
        3. 🧠 The wild history/science behind it
        4. 😬 The twist you didn’t see coming
        5. 🎤 Final punchline + comment bait
    Engagement: Visual metaphors, irony, questions, dramatic zooms, and reaction bait
    Impact: Create "Wait… this changes everything" moments that people can’t stop thinking about
    Ethics: Keep it factual, no fear-bait or fake-outs — truth is weird enough

    LIST OF IMAGE STYLES NAMES: {image_style_list}

    FORMAT YOUR RESPONSE USING THIS JSON STRUCTURE:

    {{
        "video_title": "Title of the video (Catchy and intriguing, emoji included)",
        "video_description": "Brief description of the video content, highlighting the fun and interesting aspects, emoji included.",
        "hashtags": ["#funfact", "#waitwhat", "#shorts"],
        "scenes": [
            {{
                "script": "Narration text for the hook — it should immediately stop the scroll with a ‘WHAT THE—?’ kind of energy.",
                "image_keywords": ["keyword1", "keyword2", "visually striking"],
                "scene_description": "Provide an extremely detailed, surprising, and aesthetically powerful visual. Include: primary subjects/objects, positioning, lighting, background elements, visual metaphor, colors, atmosphere, and texture. It must create instant curiosity and visual chaos or wonder.",
                "image_to_video": "Describe how the static image should animate or move to feel alive, tense, or dramatic.",
                "image_style_name": "Style of the image, chosen from {image_style_list}"
            }},
            {{
                "script": "Narration text for scene 1 — explaining what most people believe, then dropping a tiny seed of doubt.",
                "image_keywords": ["keyword1", "keyword2", "illustrative"],
                "scene_description": "Visual setup of the normal expectation or myth — make it almost TOO clean or obvious. Foreshadow the twist subtly.",
                "image_to_video": "Suggest a slow pan or zoom that builds suspense.",
                "image_style_name": "Style of the image, chosen from {image_style_list}"
            }},
            {{
                "script": "Narration text for scene 2 — the reveal begins. Surprise, irony, or bizarre info starts here.",
                "image_keywords": ["keyword1", "keyword2", "illustrative"],
                "scene_description": "The moment of ‘wait WHAT?’ Use contrast — show chaos, weirdness, or reversal of expectations.",
                "image_to_video": "Fast punch-in or zoom burst, maybe a visual glitch or flash.",
                "image_style_name": "Style of the image, chosen from {image_style_list}"
            }}
        ],
        "music_suggestion": "Upbeat, punchy, maybe a bit chaotic or glitchy — something that matches sudden twists and unexpected facts."
    }}

    IMPORTANT SCENE CREATION GUIDELINES:
    - Must have at least 9 unique scene beats, including a scroll-stopping hook and a strong, witty call-to-action conclusion.
    - Each scene must feel like it reveals a new layer of “What the…?” without stalling or repeating info.
    - Hook should be max 2–4 seconds — fast, clear, loud, and wild.
    - Append to the final scene's script: “Now that you know this, who else do you think should? Tag a friend in the comments who you think would find this fascinating!”

    SCENE DESCRIPTION GUIDELINES:
    - Must include strong contrasts, visually striking composition, and bold lighting
    - Describe visual space clearly — foreground/midground/background with intentional balance
    - Must support dynamic animation with movement opportunities (zoom, rotate, glitch, etc.)
    - Should be designed to look epic or memeable, even when paused

visual_prompt: |
    Create a stunning, high-quality, story-driven image for a short-form video scene using the following specifications:

    SCENE DESCRIPTION: {scene_description}
    SCRIPT: {script}
    IMAGE STYLE GUIDE: {image_style_guide}

    ESSENTIAL VISUAL ELEMENTS:
    - Must include: {image_keywords}
    - Image style: {image_style_guide}
    - Must visually reflect the emotion, surprise, or tension described in the script
    - Composition should support the scene’s narrative flow and character dynamics
    - Use visual storytelling techniques like contrast, exaggeration, or irony to elevate the scene

    TECHNICAL SPECIFICATIONS:
    - 9:16 vertical format optimized for TikTok, YouTube Shorts, and Reels
    - Extremely detailed, sharp image with cinematic clarity
    - Colorful and eye-catching — designed to stop scrolling within 1 second
    - Absolutely NO logos, watermarks, or platform-specific elements

    COLOR AND COMPOSITION:
    - Use the image style guide to define lighting, tone, and texture
    - Bold contrast between foreground and background to spotlight key subjects
    - Use lighting direction (e.g., rim light, glow, spotlight) to add mood or drama
    - Apply dynamic visual hierarchy — main subject should pop instantly
    - Space the image to support motion, zoom, or panning effects

    HOOKING & EMOTION:
    - Design the scene to be emotionally expressive — curiosity, surprise, tension, humor
    - Include an intriguing visual cue or “wait, what?” element that reinforces the script twist
    - Think meme-ability, shock factor, or cinematic irony — even if paused, it should tell a story
    - Bonus: Consider how a surprising visual contradiction or metaphor can make the viewer pause and think (e.g., a banana glowing like radioactive material)

    ANIMATION CONTEXT:
    This image will be animated with: {image_to_video}. Ensure space and composition support this movement type (zoom, camera shake, pan, etc.) without losing clarity or emotional impact.

    GOAL:
    Create a single, vivid, story-rich image that instantly hooks the viewer, aligns tightly with the narration, and is visually built to be animated. This image should feel like a frame from a fast-paced, mind-blowing story — not just an illustration.

image_style_guide:
  "Pop Culture Collage": "Colorful, playful layout with pop art vibes, mixed real-life photos and stickers, bold text, emoji overlays, mimicking meme-like or TikTok aesthetic, vibrant and chaotic energy"
  "Street Style Comic": "Modern comic book feel, heavy outlines, dramatic expressions, motion lines, bold fonts, vibrant colors, capturing dynamic emotional reactions and punchlines"
  "Psychology Snapshot": "Polaroid or scrapbook-style visuals, cut-out human faces or silhouettes, layered with handwritten text or notes, emotional facial expressions and thought-bubble effects"
  "Bold Typography Poster": "Giant text as a focal point, minimalist background, dramatic emphasis on hook lines or punchlines, perfect for shocking truths or 'Did you know?' facts"
  "Vintage Magazine Cutout": "1990s/early 2000s tabloid-style image collage, grainy photo textures, sensational text overlays, a mix of shock, humor, and nostalgia"
  "Everyday Zoom-In": "Macro shots of everyday objects or body parts, with overlaid diagrams or arrows, highlighting hidden details or surprising interpretations"
  "Viral Meme Overlay": "TikTok-style subtitles, face emojis, expressive eyes/mouth effects, motion blur or zoom for emphasis, short-form attention-grabbing design"
  "Emotional Color Pop": "High contrast portraits or objects with one strong pop color, focused lighting, perfect for psychological truths, personality tests, or emotional themes"
  "Digital Surrealism": "Hyperreal edits with dreamlike or twisted realism, floating objects, liquid distortions, unexpected juxtapositions — perfect for visualizing weird facts or odd truths"
  "Hyper Glitch Aesthetic": "Glitched-out visuals, chromatic aberration, VHS texture overlays, distorted fonts, cyberpunk colors — great for tech, conspiracy, or ‘broken reality’ themes"
  "Moody Cinematic Frame": "Dark, atmospheric lighting with shallow depth of field, dramatic shadows and spotlighting — perfect for emotional turns or eerie truths"
  "Mixed Media Reality": "Combines photography, stickers, sketch lines, AR-style overlays, and digital doodles — TikTok collage-style realism with storytelling layers"
